## Generated by Rookframe SDK 0.9.2. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/integration_result.gd"
enum State { UNAVAILABLE, SIGNED_OUT, SIGNED_IN, EXPIRED }
var state: State
func _init(result: Dictionary) -> void:
	super(result)
	state = result.get("state", State.UNAVAILABLE)
