## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted

const ActorId = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/actor_id.gd")
var id: ActorId
var data: Variant
func _init(value: Dictionary) -> void:
	id = ActorId.new(value.id)
	data = value.data
