## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/service_scope.gd")
const PendingOperation = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/pending_operation.gd")
const AuthenticationResult = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/authentication_result.gd")

var _scope: ServiceScope
var _launch: PendingOperation
var _final: AuthenticationResult
func _init(scope: ServiceScope, started: Dictionary) -> void:
	_scope = scope
	_launch = PendingOperation.new(scope, started)
func poll() -> AuthenticationResult:
	if _final != null:
		return _final
	var result: Dictionary = _launch._consume()
	if result.get("ready", true) and result.get("ok", false):
		var transaction: String = result.get("text", "")
		result = _scope._host.PollAuthentication(transaction)
	var status: AuthenticationResult = AuthenticationResult.new(result)
	if status.ready:
		_final = status
	return status
