## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/service_scope.gd")
const AuthenticationProviderDefinition = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/authentication_provider_definition.gd")
const AuthenticationProvider = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/authentication_provider.gd")

var _scope: ServiceScope
func _init(scope: ServiceScope) -> void:
	_scope = scope
func provider(definition: AuthenticationProviderDefinition) -> AuthenticationProvider:
	return AuthenticationProvider.new(_scope, definition.name)
