## Generated by Rookframe SDK 0.8.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/service_scope.gd")
const IntegrationResult = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/integration_result.gd")

var _scope: ServiceScope
func _init(scope: ServiceScope) -> void:
	_scope = scope
func open(url: String) -> IntegrationResult:
	return IntegrationResult.new(await _scope._complete(_scope._host.OpenBrowserLink(url)))
