## Generated by Rookframe SDK 0.9.2. Regenerate with `rookframe facade`.
extends RefCounted

const Contribution = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/contribution.gd")
var _host: Object
var _slot: String

func _init(host: Object, slot: String) -> void:
	_host = host
	_slot = slot

## Append an authored contribution in Package-local order. Repeated scenes are idempotent.
func push(entry: Contribution) -> void:
	_host.RegisterContribution(_slot, entry.scene)
