## Generated by Rookframe SDK 0.4.0. Regenerate with `rookframe facade`.
extends RefCounted

const ContentReference = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/content_reference.gd")
var reference: ContentReference
var title: String
var kind: String
var available: bool
func _init(value: Dictionary) -> void:
	reference = ContentReference.new(value.packageId, value.localId)
	title = value.displayName
	kind = value.type
	available = value.available
