## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends Resource

const FeedbackAction = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/feedback_action.gd")
@export var title: String
@export_multiline var message: String
@export var actions: Array[FeedbackAction] = []
