## Generated by Rookframe SDK 0.4.0. Regenerate with `rookframe facade`.
extends Node

const SDK = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/package_sdk_facade.gd")
## Available during start() in an installed World.
var sdk: SDK


func _ready() -> void:
	if has_meta("rookframe_sdk"):
		sdk = SDK.new(get_meta("rookframe_sdk"))
		if not has_meta("rookframe_cleanup"):
			start()


## Override for Package setup. Godot owns the surrounding Node lifecycle.
func start() -> void:
	pass


func cleanup_world(completed: Callable) -> void:
	cleanup(SDK.Cleanup.new(completed))

## Override when this executable root has World-specific cleanup.
func cleanup(operation: SDK.Cleanup) -> void:
	operation.complete()
