## Generated by Rookframe SDK 0.9.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/service_scope.gd")
const ServiceDefinition = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/service_definition.gd")
const NamedService = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/named_service.gd")
const Account = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/account.gd")

var _scope: ServiceScope
func _init(scope: ServiceScope) -> void:
	_scope = scope
func service(definition: ServiceDefinition, account: Account = null) -> NamedService:
	return NamedService.new(_scope, definition.name, account)
