extends RefCounted

## Generated by Rookframe SDK 0.1.1. Regenerate with `rookframe facade`.
## Package-scoped SDK Edition 2027; this file ships with the Package.
const SDK_EDITION := "2027"
const MINIMUM_REVISION := 1
const AUTHOR_ROOT := "res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/"

var _host: Object


## The World binds the calling Package before normal Node setup.
func bind(host: Object) -> void:
	_host = host


## The stable Package identity, independent of build and installation.
func package_id() -> String:
	return _host.PackageId() if _host != null else "aae579da-5392-4507-8eaa-0d918af58076"


## The current resource root in the editor or selected immutable profile.
func package_root() -> String:
	return _host.PackageRoot() if _host != null else AUTHOR_ROOT


## The current Presentation experience (desktop, phone or tablet).
func presentation_experience() -> String:
	return _host.PresentationExperience() if _host != null else "desktop"


## Open an authored Control in the host-owned Extension Surface.
func open_extension_surface(content: Control) -> bool:
	return _host != null and _host.OpenExtensionSurface(content)


## Add one authored entry to the left or right Rail's Package slot.
func mount_rail(rail: String, content: Control) -> bool:
	return _host != null and _host.MountRailContribution(rail, content)
