## Generated by Rookframe SDK 0.2.0. Regenerate with `rookframe facade`.
extends RefCounted

const Rail = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/rail.gd")
const Rails = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/rails.gd")
const WindowButton = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/window_button.gd")
const ExtensionSurface = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/extension_surface.gd")
const SDK_EDITION := "2027"
const MINIMUM_REVISION := 1

var _host: Object
var _rails: Rails
## Package-scoped access to the workspace Rails.
var rails: Rails:
	get:
		return _rails


func _init(host: Object) -> void:
	_host = host
	_rails = Rails.new(host)


## Stable Package identity, independent of builds and installations.
func package_id() -> String:
	return _host.PackageId()


## Current admitted resource root for this Package.
func package_root() -> String:
	return _host.PackageRoot()


## Current desktop, tablet or phone Presentation experience.
func presentation_experience() -> String:
	return _host.PresentationExperience()
