## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/service_scope.gd")
## Internal polling bridge. Completed results are retained; native IDs are consumed once.
var _scope: ServiceScope
var _last: Dictionary
var _id: int
func _init(scope: ServiceScope, started: Dictionary) -> void:
	_scope = scope
	_last = started
	_id = started.get("id", 0)
func _consume() -> Dictionary:
	if not _last.get("ready", true):
		_last = _scope._host.PollService(_id)
	return _last
