## Generated by Rookframe SDK 0.2.0. Regenerate with `rookframe facade`.
extends Control

const SDK = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/package_sdk_facade.gd")
## Bound automatically before compose().
var sdk: SDK


func compose_presentation(host: Object) -> Control:
	sdk = SDK.new(host)
	compose()
	return self


## Override to register this Presentation's authored UI through the SDK.
func compose() -> void:
	pass
