## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/service_scope.gd")
const PendingOperation = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/pending_operation.gd")
const ResponseResult = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/response_result.gd")

var _pending: PendingOperation
func _init(scope: ServiceScope, started: Dictionary) -> void:
	_pending = PendingOperation.new(scope, started)
func poll() -> ResponseResult:
	return ResponseResult.new(_pending._consume())
