## Generated by Rookframe SDK 0.8.0. Regenerate with `rookframe facade`.
extends RefCounted

const RookId = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/rook_id.gd")
const SceneResult = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/scene_result.gd")
const DistanceResult = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/distance_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

func current() -> SceneResult:
	return SceneResult.new(_host.CurrentScene())
func distance(from: RookId, to: RookId) -> DistanceResult:
	return DistanceResult.new(_host.RookDistance(from.value, to.value))
