## Generated by Rookframe SDK 0.5.0. Regenerate with `rookframe facade`.
extends RefCounted

const SceneId = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/scene_id.gd")
var id: SceneId
var name: String
func _init(value: Dictionary) -> void:
	id = SceneId.new(value.id)
	name = value.name
