## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/service_scope.gd")
const BytesOperation = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/bytes_operation.gd")
const IntegrationResult = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/integration_result.gd")

var _scope: ServiceScope
var _id: int
func _init(scope: ServiceScope, id: int) -> void:
	_scope = scope
	_id = id
func read(maximum_bytes: int = 65536) -> BytesOperation:
	return BytesOperation.new(_scope, _scope._host.ReadServiceStream(_id, maximum_bytes))
func close() -> IntegrationResult:
	return IntegrationResult.new(_scope._host.CloseServiceStream(_id))
