## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/setting.gd"
## Values use the existing protected store and never enter an ordinary draft/copy.

const AuthenticationProviderDefinition = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/authentication_provider_definition.gd")
## Optional provider for Rookframe-owned sign-in/refresh/clear controls.
@export var authentication: AuthenticationProviderDefinition
