## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/service_scope.gd")
const SecretEntry = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/secret_entry.gd")
const SecretSetting = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/secret_setting.gd")

var _scope: ServiceScope
var _area: String
func _init(scope: ServiceScope, area: String) -> void:
	_scope = scope
	_area = area
func entry(name: String) -> SecretEntry:
	return SecretEntry.new(_scope, _area, name)
func setting(descriptor: SecretSetting) -> SecretEntry:
	return entry(descriptor.key)
