## Generated by Rookframe SDK 0.8.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/service_scope.gd")
const SecretArea = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/secret_area.gd")

var _user: SecretArea
var _world: SecretArea
var user: SecretArea:
	get:
		return _user
var world: SecretArea:
	get:
		return _world
func _init(scope: ServiceScope) -> void:
	_user = SecretArea.new(scope, "user")
	_world = SecretArea.new(scope, "world")
