## Generated by Rookframe SDK 0.6.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/setting.gd"
## Values use the existing protected store and never enter an ordinary draft/copy.
