## Generated by Rookframe SDK 0.5.0. Regenerate with `rookframe facade`.
extends RefCounted

const TextSetting = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/text_setting.gd")
const ToggleSetting = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/toggle_setting.gd")
const IntegerSetting = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/integer_setting.gd")
const NumberSetting = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/number_setting.gd")
const ObjectSetting = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/object_setting.gd")
const ArraySetting = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/array_setting.gd")

var _values: Dictionary
func _init(values: Dictionary = {}) -> void:
	_values = values.duplicate(true)

func _copy() -> Dictionary:
	return _values.duplicate(true)

func text(setting: TextSetting) -> String:
	return _values.get(setting.key, "")

func toggle(setting: ToggleSetting) -> bool:
	return _values.get(setting.key, false)

func integer(setting: IntegerSetting) -> int:
	return _values.get(setting.key, 0)

func number(setting: NumberSetting) -> float:
	return _values.get(setting.key, 0.0)

func object(setting: ObjectSetting) -> Dictionary:
	var value: Dictionary = _values.get(setting.key, {})
	return value.duplicate(true)

func array(setting: ArraySetting) -> Array:
	var value: Array = _values.get(setting.key, [])
	return value.duplicate(true)
