## Generated by Rookframe SDK 0.5.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/settings_values.gd"
const SettingsScope = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/settings_scope.gd")
var scope: SettingsScope.Kind
func _init(candidate_scope: SettingsScope.Kind, values: Dictionary) -> void:
	super(values)
	scope = candidate_scope
