## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted
const ServiceScope = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/service_scope.gd")
const PendingOperation = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/pending_operation.gd")
const StreamResult = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/stream_result.gd")
const ScopedStream = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/scoped_stream.gd")

var _scope: ServiceScope
var _pending: PendingOperation
var _stream: ScopedStream
func _init(scope: ServiceScope, started: Dictionary) -> void:
	_scope = scope
	_pending = PendingOperation.new(scope, started)
func poll() -> StreamResult:
	var result: Dictionary = _pending._consume()
	if _stream == null and result.get("ready", true) and result.get("ok", false):
		_stream = ScopedStream.new(_scope, result.get("id", 0))
	return StreamResult.new(result, _stream)
