## Generated by Rookframe SDK 0.6.0. Regenerate with `rookframe facade`.
extends RefCounted

const SystemRecordId = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/system_record_id.gd")
const SystemRecordResult = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/system_record_result.gd")
const SystemRecordListResult = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/system_record_list_result.gd")
const OperationResult = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/operation_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

func list(type_name: String = "") -> SystemRecordListResult:
	return SystemRecordListResult.new(_host.ListSystemRecords(type_name))
func read(id: SystemRecordId) -> SystemRecordResult:
	return SystemRecordResult.new(_host.ReadSystemRecord(id.value))
func create(type_name: String, data: Variant) -> SystemRecordResult:
	return SystemRecordResult.new(_host.CreateSystemRecord(type_name, data))
func update(id: SystemRecordId, data: Variant) -> SystemRecordResult:
	return SystemRecordResult.new(_host.UpdateSystemRecord(id.value, data))
func delete(id: SystemRecordId) -> OperationResult:
	return OperationResult.new(_host.DeleteSystemRecord(id.value))
