## Generated by Rookframe SDK 0.9.0. Regenerate with `rookframe facade`.
extends RefCounted

const SystemRecordId = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/system_record_id.gd")
var id: SystemRecordId
var type_name: String
var data: Variant
func _init(value: Dictionary) -> void:
	id = SystemRecordId.new(value.id)
	type_name = value.type_name
	data = value.data
