## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends "res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/setting.gd"
@export var default_value: PackedStringArray = []
@export var minimum_items: int = 0
@export var maximum_items: int = 256
@export var minimum_length: int = 0
@export var maximum_length: int = 4096
