## Generated by Rookframe SDK 0.6.0. Regenerate with `rookframe facade`.
extends RefCounted

const OperationResult = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/operation_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

var _capability: String
func configure(name: String) -> void:
	_capability = name
## Integration boundary reserved for the owning project; no predicted gameplay result.
func status() -> OperationResult:
	return OperationResult.new(_host.CapabilityStatus(_capability))
