## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends Resource

const ExtensionSurface = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/extension_surface.gd")
## Authored Button scene, using the public UI Kit Theme and assets.
@export var button_scene: PackedScene
## The window to open when this entry is activated.
@export var window: ExtensionSurface
