## Generated by Rookframe SDK 0.7.0. Regenerate with `rookframe facade`.
extends RefCounted

const ExtensionSurface = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/extension_surface.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

func open(surface: ExtensionSurface) -> void:
	_host.OpenWindow(surface.scene)
