## Generated by Rookframe SDK 0.6.0. Regenerate with `rookframe facade`.
extends RefCounted

const OperationResult = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/operation_result.gd")
const DataResult = preload("res://rookframe/packages/aae579da-5392-4507-8eaa-0d918af58076/sdk/data_result.gd")

var _host: Object
func _init(host: Object) -> void:
	_host = host

## The authority's one live value for this Package. Null means never committed.
func read() -> DataResult:
	return DataResult.new(_host.ReadWorldData())
## Root replacement commits implicitly; invalid input leaves the prior save intact.
func replace(value: Variant) -> OperationResult:
	return OperationResult.new(_host.ReplaceWorldData(value))
## Explicitly commit mutations made in place to the live value.
func commit() -> OperationResult:
	return OperationResult.new(_host.CommitWorldData())
